{{- range $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $secret.namespace | default "default" }}
type: Opaque
data:
{{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
---
{{- end }}

